export class AtApplicants {
  constructor(
    public id?: number,
    public name?: string,
    public surname?: string,
    public middleName?: string,
    public maidenName?: string,
    public gender?: string,
    public birthdate?: any,
    public materialStatus?: string,
    public address?: string,
    public employed?: string,
    public description?: string,
    public employementPosition?: string,
    public industry?: string,
    public phoneNumber?: string,
    public email?: string,
    public imageLink?: string,
    public idCity?: number,
    public idCityName?: string,
    public idQualifcation?: number,
    public idQualificationName?: string,
    public idEmployee?: number,
    public idUser?: number,
    public createdBy?: string,
    public createdAt?: any,
    public updatedBy?: string,
    public updatedAt?: any,
    public imageBlob?: any,
    public imageBlobContentType?: string,
    public driverLicence?: string,
    public isBlacklisted?: string
  ) {
  }
}
